#version: "3.8"

services:
  django:
    build:
      context: ..
      dockerfile: ./deployment/Dockerfile
    #image: ${REGISTRY}/${IMAGE_NAME}/dj_test:${GITHUB_SHA_SHORT}
    image: ${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA_SHORT}
