# Generated by Django 5.1 on 2024-09-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Gambar'),
        ),
    ]
